version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/ui'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'gomod'
    directory: '/backend'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
