# https://docs.buf.build/ci-cd/github-actions
name: buf-pull-request
on:
  pull_request:
    paths:
      - 'proto/**'
      - '.github/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: "proto"
          # The 'main' branch of the GitHub repository that defines the module.
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main,subdir=proto"