name: go-test

on:
  push:
    paths:
      - 'backend/**'
      - 'proto/**'
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Build
        run: cd backend && go build -v ./...

      - name: Test
        run: cd backend && go test --race -v ./...