name: reviewdog
on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/**'
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          # Can pass --config flag to change golangci-lint behavior and target
          # directory.
          # golangci_lint_flags: "--config=.golangci.yml"
          workdir: backend/
